name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_FIREBASE_API_KEY: ${{ AIzaSyDz-rjW6Z0M53EIy-f-oQ0u4UBnmqS1eGc }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ mini-forum-ec815.firebaseapp.com }}
          VITE_FIREBASE_PROJECT_ID: ${{ mini-forum-ec815 }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ mini-forum-ec815.firebasestorage.app }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ 757219389665 }}
          VITE_FIREBASE_APP_ID: ${{ 1:757219389665:web:103e7561ad97ef7c8987a0 }}
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ 1//0c0_D1r-qB9oICgYIARAAGAwSNwF-L9IrEjU4BCHEpemzPK4lmAHWjik2jyvjNCDYeTtWy-Vz9CGpsXEEcl_Ydnk8BZ9K1XdBwhI }}
        run: |
          firebase deploy --only hosting --non-interactive
